[package]
name = "hamming_code_simd"
version = "0.1.0"
authors = ["Juxhin Dyrmishi Brigjaj <juxhinbox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
